const tools=[
["age","🧮","Age Calculator","Calculate age in years, months and days.","math"],["date","📅","Date Difference","Find the days between two dates.","utility"],["words","📝","Word Counter","Count words, characters and lines.","text"],["unit","📏","Unit Converter","Convert length and weight units.","utility"],["percent","％","Percentage Calculator","Three useful percentage calculations.","math"],["discount","🏷️","Discount Calculator","Find savings and final sale price.","math"],["tip","💵","Tip Calculator","Calculate tip, total and split amount.","math"],["average","📊","Average Calculator","Find the average of a list of numbers.","math"],["bmi","⚖️","BMI Calculator","Calculate body mass index.","math"],["loan","🏦","Loan Calculator","Estimate a monthly loan payment.","math"],["currency","💱","Currency Calculator","Multiply an amount by a rate you provide.","math"],["password","🔐","Password Generator","Generate a strong random password.","security"],["strength","🛡️","Password Checker","Check basic password strength locally.","security"],["qr","📱","QR Generator & Scanner","Generate a QR code or scan one with your camera.","utility"],["case","🔤","Text Case Converter","Uppercase, lowercase and title case.","text"],["reverse","↔️","Text Reverser","Reverse text instantly.","text"],["spaces","🧹","Remove Extra Spaces","Clean repeated spaces and line breaks.","text"],["slug","🔗","Slug Generator","Create clean URL slugs.","text"],["base64","🧩","Base64 Encoder","Encode or decode Base64 text.","utility"],["random","🎲","Random Number","Generate a random number in a range.","utility"],["time","⏱️","Time Converter","Convert seconds, minutes and hours.","utility"],["length","📐","Length Converter","Convert common length units.","utility"],["temp","🌡️","Temperature Converter","Convert Celsius, Fahrenheit and Kelvin.","utility"],["countdown","⏳","Countdown Timer","Create a simple countdown in your browser.","utility"],["textsort","🔠","Text Sorter","Sort lines alphabetically.","text"],["duplicate","🧬","Remove Duplicates","Remove duplicate lines from text.","text"],["json","🧾","JSON Formatter","Format JSON with readable indentation.","utility"],["url","🌐","URL Encoder","Encode or decode URL text.","utility"],["binary","💻","Binary Converter","Convert text to binary and back.","utility"],["hex","🔢","Hex Converter","Convert text to hexadecimal and back.","utility"],["files","📁","My Files","Choose a file from your computer and keep a local record.","utility"]
];

const grid=document.getElementById("toolGrid");
grid.innerHTML=tools.map(t=>`<article class="card" data-cat="${t[4]}" data-name="${t[2].toLowerCase()}"><div class="emoji">${t[1]}</div><h3>${t[2]}</h3><p>${t[3]}</p><button class="open" onclick="openTool('${t[0]}')">Open tool</button></article>`).join("");

document.querySelectorAll(".chip").forEach(b=>b.onclick=()=>{document.querySelectorAll(".chip").forEach(x=>x.classList.remove("active"));b.classList.add("active");filter()});
document.getElementById("search").oninput=filter;
function filter(){const q=document.getElementById("search").value.toLowerCase(),cat=document.querySelector(".chip.active").dataset.cat;document.querySelectorAll(".card").forEach(c=>c.style.display=(cat==="all"||c.dataset.cat===cat)&&c.dataset.name.includes(q)?"block":"none")}

document.getElementById("themeBtn").onclick=()=>{document.body.classList.toggle("dark");localStorage.setItem("tnDark",document.body.classList.contains("dark"))};
if(localStorage.getItem("tnDark")==="true")document.body.classList.add("dark");

const panel=document.getElementById("toolPanel");
const HISTORY_KEY="tnHistoryV2";
const FILE_KEY="tnFileRecordsV1";
let cameraStream=null, cameraTimer=null;

function shell(title,body){panel.innerHTML=`<div class="toolTop"><h2>${title}</h2><button class="close" onclick="closeTool()">✕ Close</button></div>${body}`;panel.classList.add("show");panel.scrollIntoView({behavior:"smooth",block:"start"})}
function closeTool(){stopCamera();panel.classList.remove("show")}
function escapeHtml(s){return String(s).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]))}
function notify(message){const box=document.getElementById("toast");if(box){box.textContent=message;box.classList.add("show");clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>box.classList.remove("show"),2600)}
if("Notification" in window && Notification.permission==="granted")new Notification("ToolNest",{body:message});}
async function enableNotifications(){if("Notification" in window&&Notification.permission==="default"){try{await Notification.requestPermission()}catch(e){}}}
function saveHistory(tool,result){if(!result)return;let h=JSON.parse(localStorage.getItem(HISTORY_KEY)||"[]");h.unshift({id:Date.now(),tool,result,time:new Date().toLocaleString()});h=h.slice(0,100);localStorage.setItem(HISTORY_KEY,JSON.stringify(h));notify("Calculation saved to your record.");renderHistory()}
function renderHistory(){const el=document.getElementById("historyList");if(!el)return;const h=JSON.parse(localStorage.getItem(HISTORY_KEY)||"[]");el.innerHTML=h.length?h.map(x=>`<div class="historyItem"><b>${escapeHtml(x.tool)}</b><span>${escapeHtml(x.result)}</span><small>${escapeHtml(x.time)}</small></div>`).join(""):"<p class='muted'>No saved calculations yet.</p>"}
function clearHistory(){localStorage.removeItem(HISTORY_KEY);renderHistory();notify("Calculation history cleared.")}
function exportHistory(){const h=JSON.parse(localStorage.getItem(HISTORY_KEY)||"[]");if(!h.length){notify("There is no history to export.");return}downloadBlob(JSON.stringify(h,null,2),"toolnest-history.json","application/json");notify("History exported.")}
function downloadBlob(content,name,type){const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}

function openTool(t){
let b="";
if(t==="age")b=`<p class="muted">You can type your date as <b>DD/MM/YYYY</b> or use the date picker.</p><div class="form"><input type="text" id="dobText" inputmode="numeric" placeholder="DD/MM/YYYY" maxlength="10"><input type="date" id="dobPicker" aria-label="Choose date"><button class="action" onclick="ageCalc()">Calculate Age</button></div><div id="r" class="result"></div>`;
if(t==="date")b=`<div class="form"><input type="date" id="d1"><input type="date" id="d2"><button class="action" onclick="dateCalc()">Calculate</button></div><div id="r" class="result"></div>`;
if(t==="words")b=`<textarea id="tx" oninput="wordCalc()" placeholder="Type or paste text..."></textarea><div id="r" class="result">Words: 0 · Characters: 0 · Lines: 0</div>`;
if(t==="unit")b=`<div class="form"><input type="number" id="uv" placeholder="Value"><select id="uf"><option value="m">Meters</option><option value="km">Kilometers</option><option value="ft">Feet</option><option value="mi">Miles</option><option value="kg">Kilograms</option><option value="g">Grams</option></select><select id="ut"><option value="m">Meters</option><option value="km">Kilometers</option><option value="ft">Feet</option><option value="mi">Miles</option><option value="kg">Kilograms</option><option value="g">Grams</option></select><button class="action" onclick="unitCalc()">Convert</button></div><div id="r" class="result"></div>`;
if(t==="percent")b=`<div class="form"><select id="pmode"><option value="of">What is X% of Y?</option><option value="is">X is what % of Y?</option><option value="change">Percentage increase/decrease</option></select></div><div class="form"><input type="number" id="pa" placeholder="X / Original"><input type="number" id="pb" placeholder="Y / New"><button class="action" onclick="percentCalc()">Calculate</button></div><div id="r" class="result"></div>`;
if(t==="discount")b=`<div class="form"><input type="number" id="pr" placeholder="Original price"><input type="number" id="di" placeholder="Discount %"><button class="action" onclick="discountCalc()">Calculate</button></div><div id="r" class="result"></div>`;
if(t==="tip")b=`<div class="form"><input type="number" id="bill" placeholder="Bill"><input type="number" id="tp" placeholder="Tip %"><input type="number" id="pp" value="1" placeholder="People"><button class="action" onclick="tipCalc()">Calculate</button></div><div id="r" class="result"></div>`;
if(t==="average")b=`<input id="av" class="fullInput" placeholder="10, 20, 30"><div class="form"><button class="action" onclick="avgCalc()">Calculate</button></div><div id="r" class="result"></div>`;
if(t==="bmi")b=`<div class="form"><input type="number" id="bh" placeholder="Height cm"><input type="number" id="bw" placeholder="Weight kg"><button class="action" onclick="bmiCalc()">Calculate</button></div><div id="r" class="result"></div>`;
if(t==="loan")b=`<div class="form"><input type="number" id="la" placeholder="Amount"><input type="number" id="lr" placeholder="Annual interest %"><input type="number" id="ly" placeholder="Years"><button class="action" onclick="loanCalc()">Calculate</button></div><div id="r" class="result"></div>`;
if(t==="currency")b=`<p class="muted">Enter the current exchange rate yourself.</p><div class="form"><input type="number" id="ca" placeholder="Amount"><input type="number" id="cr" placeholder="Rate"><button class="action" onclick="currencyCalc()">Calculate</button></div><div id="r" class="result"></div>`;
if(t==="password")b=`<div class="form"><input type="number" id="pl" value="16" min="6" max="64"><button class="action" onclick="passGen()">Generate</button></div><input id="po" class="fullInput" readonly><div class="form"><button class="action" onclick="copyText(po.value)">Copy</button></div>`;
if(t==="strength")b=`<input id="spass" type="password" class="fullInput" oninput="strengthCalc()" placeholder="Enter password"><div id="r" class="result"></div>`;
if(t==="qr")b=`<input id="qv" class="fullInput" placeholder="Text or URL"><div class="form"><button class="action" onclick="qrGen()">Generate QR</button><button class="action secondary" onclick="startCamera()">📷 Open Camera</button><button class="action secondary" onclick="stopCamera()">Stop Camera</button></div><div class="cameraWrap"><video id="qrVideo" autoplay playsinline></video><div class="scanLine"></div></div><p id="cameraMsg" class="muted"></p><div id="r" class="qrResult"></div>`;
if(t==="case")b=`<textarea id="ct" placeholder="Enter text..."></textarea><div class="form"><button class="action" onclick="ct.value=ct.value.toUpperCase()">UPPERCASE</button><button class="action" onclick="ct.value=ct.value.toLowerCase()">lowercase</button><button class="action" onclick="ct.value=ct.value.toLowerCase().replace(/\\b\\w/g,x=>x.toUpperCase())">Title Case</button></div>`;
if(t==="reverse")b=`<textarea id="rt"></textarea><button class="action" onclick="rt.value=[...rt.value].reverse().join('')">Reverse</button>`;
if(t==="spaces")b=`<textarea id="st"></textarea><button class="action" onclick="st.value=st.value.replace(/\\s+/g,' ').trim()">Clean</button>`;
if(t==="slug")b=`<input id="si" class="fullInput" placeholder="Article title"><div class="form"><button class="action" onclick="so.value=si.value.toLowerCase().trim().replace(/[^\\w\\s-]/g,'').replace(/[\\s_-]+/g,'-').replace(/^-+|-+$/g,'')">Generate</button></div><input id="so" class="fullInput" readonly>`;
if(t==="base64")b=`<textarea id="b6"></textarea><div class="form"><button class="action" onclick="b6.value=btoa(unescape(encodeURIComponent(b6.value)))">Encode</button><button class="action" onclick="b6.value=decodeURIComponent(escape(atob(b6.value)))">Decode</button></div>`;
if(t==="random")b=`<div class="form"><input type="number" id="mn" value="1"><input type="number" id="mx" value="100"><button class="action" onclick="randomCalc()">Generate</button></div><div id="r" class="result"></div>`;
if(t==="time")b=`<div class="form"><input type="number" id="tv" placeholder="Value"><select id="tf"><option value="s">Seconds</option><option value="m">Minutes</option><option value="h">Hours</option></select><button class="action" onclick="timeCalc()">Convert</button></div><div id="r" class="result"></div>`;
if(t==="length")b=`<div class="form"><input type="number" id="lv" placeholder="Value"><select id="lf"><option value="m">Meters</option><option value="km">Kilometers</option><option value="ft">Feet</option><option value="mi">Miles</option></select><select id="lt"><option value="m">Meters</option><option value="km">Kilometers</option><option value="ft">Feet</option><option value="mi">Miles</option></select><button class="action" onclick="lengthCalc()">Convert</button></div><div id="r" class="result"></div>`;
if(t==="temp")b=`<div class="form"><input type="number" id="tvv" placeholder="Value"><select id="tfm"><option value="c">Celsius</option><option value="f">Fahrenheit</option><option value="k">Kelvin</option></select><select id="ttm"><option value="c">Celsius</option><option value="f">Fahrenheit</option><option value="k">Kelvin</option></select><button class="action" onclick="tempCalc()">Convert</button></div><div id="r" class="result"></div>`;
if(t==="countdown")b=`<div class="form"><input type="number" id="sec" value="60"><button class="action" onclick="countdown()">Start</button></div><div id="r" class="result">60</div>`;
if(t==="textsort")b=`<textarea id="sortt" placeholder="One item per line"></textarea><button class="action" onclick="sortt.value=sortt.value.split('\\n').sort((a,b)=>a.localeCompare(b)).join('\\n')">Sort</button>`;
if(t==="duplicate")b=`<textarea id="dupt"></textarea><button class="action" onclick="dupt.value=[...new Set(dupt.value.split('\\n'))].join('\\n')">Remove duplicates</button>`;
if(t==="json")b=`<textarea id="jt" placeholder='{"name":"ToolNest"}'></textarea><button class="action" onclick="try{jt.value=JSON.stringify(JSON.parse(jt.value),null,2);notify('JSON formatted.')}catch(e){notify('Invalid JSON.')} ">Format JSON</button>`;
if(t==="url")b=`<textarea id="urlt"></textarea><div class="form"><button class="action" onclick="urlt.value=encodeURIComponent(urlt.value)">Encode</button><button class="action" onclick="urlt.value=decodeURIComponent(urlt.value)">Decode</button></div>`;
if(t==="binary")b=`<textarea id="bit"></textarea><div class="form"><button class="action" onclick="bit.value=[...bit.value].map(c=>c.charCodeAt(0).toString(2).padStart(8,'0')).join(' ')">Text → Binary</button><button class="action" onclick="bit.value=bit.value.split(/\\s+/).map(x=>String.fromCharCode(parseInt(x,2))).join('')">Binary → Text</button></div>`;
if(t==="hex")b=`<textarea id="hext"></textarea><div class="form"><button class="action" onclick="hext.value=[...hext.value].map(c=>c.charCodeAt(0).toString(16).padStart(2,'0')).join(' ')">Text → Hex</button><button class="action" onclick="hext.value=hext.value.split(/\\s+/).map(x=>String.fromCharCode(parseInt(x,16))).join('')">Hex → Text</button></div>`;
if(t==="files")b=`<p class="muted">Select any file from your computer. The file stays in your browser; its contents are not uploaded to a server by ToolNest.</p><div class="form"><input type="file" id="fileInput" onchange="saveFileRecord(this.files[0])"></div><div id="fileRecords" class="fileRecords"></div>`;
shell(tools.find(x=>x[0]===t)[1]+" "+tools.find(x=>x[0]===t)[2],b);
if(t==="age"){const p=document.getElementById("dobPicker"),txt=document.getElementById("dobText");p.max=new Date().toISOString().slice(0,10);p.onchange=()=>{if(p.value){const [y,m,d]=p.value.split("-");txt.value=`${d}/${m}/${y}`}};txt.oninput=()=>{const v=txt.value.trim();const m=v.match(/^(\\d{1,2})[\\/-](\\d{1,2})[\\/-](\\d{4})$/);if(m){const [_,d,mo,y]=m;p.value=`${y}-${String(mo).padStart(2,"0")}-${String(d).padStart(2,"0")}`}}}
if(t==="files")renderFileRecords();
}

function validNumber(...xs){return xs.every(x=>Number.isFinite(Number(x)))}
function ageCalc(){let raw=dobText.value.trim(),d;if(/^\\d{4}-\\d{2}-\\d{2}$/.test(raw))d=new Date(raw+"T00:00:00");else{const m=raw.match(/^(\\d{1,2})[\\/-](\\d{1,2})[\\/-](\\d{4})$/);if(m)d=new Date(`${m[3]}-${String(m[2]).padStart(2,"0")}-${String(m[1]).padStart(2,"0")}T00:00:00`)}const n=new Date();if(!d||Number.isNaN(d.getTime())||d>n){r.textContent="Enter a valid past date (DD/MM/YYYY).";return}let y=n.getFullYear()-d.getFullYear(),m=n.getMonth()-d.getMonth(),days=n.getDate()-d.getDate();if(days<0){m--;days+=new Date(n.getFullYear(),n.getMonth(),0).getDate()}if(m<0){y--;m+=12}const result=`Age: ${y} years, ${m} months, ${days} days`;r.textContent=result;saveHistory("Age Calculator",result)}
function dateCalc(){if(!d1.value||!d2.value){r.textContent="Choose both dates.";return}const result=`Difference: ${Math.abs((new Date(d2.value)-new Date(d1.value))/86400000)} days`;r.textContent=result;saveHistory("Date Difference",result)}
function wordCalc(){const x=tx.value,result=`Words: ${x.trim()?x.trim().split(/\s+/).length:0} · Characters: ${x.length} · Lines: ${x?x.split("\n").length:0}`;r.textContent=result}
const units={m:1,km:1000,ft:.3048,mi:1609.344,kg:1,g:.001};
function unitCalc(){if(!validNumber(uv.value)||!units[uf.value]||!units[ut.value]){r.textContent="Enter a valid value.";return}const result=`Result: ${(+uv.value*units[uf.value]/units[ut.value]).toFixed(6)}`;r.textContent=result;saveHistory("Unit Converter",result)}
function percentCalc(){const a=Number(pa.value),b=Number(pb.value),mode=pmode.value;if(!Number.isFinite(a)||!Number.isFinite(b)){r.textContent="Enter both numbers.";return}let result;if(mode==="of")result=`${a}% of ${b} = ${(a/100*b).toFixed(2)}`;else if(mode==="is")result=b===0?"Cannot divide by zero.":`${a} is ${(a/b*100).toFixed(2)}% of ${b}`;else result=b===0?"Original value cannot be zero.":`Change from ${a} to ${b}: ${((b-a)/a*100).toFixed(2)}%`;r.textContent=result;saveHistory("Percentage Calculator",result)}
function discountCalc(){const p=+pr.value,d=+di.value;if(!validNumber(p,d)){r.textContent="Enter valid values.";return}const s=p*d/100,result=`Save ${s.toFixed(2)} · Final ${(+p-s).toFixed(2)}`;r.textContent=result;saveHistory("Discount Calculator",result)}
function tipCalc(){const b=+bill.value,t=+tp.value,n=Math.max(1,+pp.value);if(!validNumber(b,t,n)){r.textContent="Enter valid values.";return}const tip=b*t/100,result=`Tip ${tip.toFixed(2)} · Total ${(b+tip).toFixed(2)} · Each ${((b+tip)/n).toFixed(2)}`;r.textContent=result;saveHistory("Tip Calculator",result)}
function avgCalc(){const a=av.value.split(",").map(Number).filter(Number.isFinite);if(!a.length){r.textContent="Enter numbers separated by commas.";return}const result=`Average: ${(a.reduce((x,y)=>x+y,0)/a.length).toFixed(2)}`;r.textContent=result;saveHistory("Average Calculator",result)}
function bmiCalc(){const h=+bh.value/100,w=+bw.value;if(h<=0||w<=0){r.textContent="Enter valid values.";return}const result=`BMI: ${(w/(h*h)).toFixed(1)}`;r.textContent=result;saveHistory("BMI Calculator",result)}
function loanCalc(){const P=+la.value,i=+lr.value/1200,n=+ly.value*12;if(P<=0||n<=0){r.textContent="Enter valid values.";return}const monthly=!i?P/n:P*i*Math.pow(1+i,n)/(Math.pow(1+i,n)-1),result=`Monthly payment: ${monthly.toFixed(2)}`;r.textContent=result;saveHistory("Loan Calculator",result)}
function currencyCalc(){const result=(+ca.value*+cr.value).toFixed(2);r.textContent=result;saveHistory("Currency Calculator",result)}
function passGen(){const c="ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789!@#$%^&*",n=Math.min(64,Math.max(6,+pl.value||16));let s="";for(let i=0;i<n;i++)s+=c[Math.floor(Math.random()*c.length)];po.value=s;notify("Password generated.")}
function strengthCalc(){const p=spass.value,n=p.length,s=(n>=8)+(n>=12)+/[A-Z]/.test(p)+/[a-z]/.test(p)+/[0-9]/.test(p)+/[^A-Za-z0-9]/.test(p);r.textContent=`Strength: ${s<3?"Weak":s<5?"Medium":"Strong"}`}
function qrGen(){if(!qv.value.trim()){r.textContent="Enter text or a URL first.";return}r.innerHTML=`<img class="qrImage" alt="QR code" src="https://api.qrserver.com/v1/create-qr-code/?size=240x240&data=${encodeURIComponent(qv.value)}"><p class="muted">QR generated successfully.</p>`;notify("QR code generated.")}
async function startCamera(){const msg=document.getElementById("cameraMsg"),video=document.getElementById("qrVideo");if(!video)return;if(!navigator.mediaDevices?.getUserMedia){msg.textContent="Camera is not supported by this browser.";return}try{await enableNotifications();cameraStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:"environment"}},audio:false});video.srcObject=cameraStream;msg.textContent="Camera is on. Point it at a QR code.";if("BarcodeDetector" in window){const detector=new BarcodeDetector({formats:["qr_code"]});cameraTimer=setInterval(async()=>{try{const codes=await detector.detect(video);if(codes.length&&codes[0].rawValue){qv.value=codes[0].rawValue;r.textContent=`Scanned: ${codes[0].rawValue}`;notify("QR code scanned successfully.");stopCamera()}}catch(e){}},500)}else msg.textContent="Camera opened, but QR scanning is not supported by this browser. You can still use the camera preview."}catch(e){msg.textContent="Camera permission was blocked. Allow camera access in your browser and try again."}}
function stopCamera(){if(cameraTimer){clearInterval(cameraTimer);cameraTimer=null}if(cameraStream){cameraStream.getTracks().forEach(t=>t.stop());cameraStream=null}const v=document.getElementById("qrVideo");if(v)v.srcObject=null}
function timeCalc(){const s=+tv.value*(tf.value==="h"?3600:tf.value==="m"?60:1),result=`Seconds ${s} · Minutes ${(s/60).toFixed(2)} · Hours ${(s/3600).toFixed(2)}`;r.textContent=result;saveHistory("Time Converter",result)}
function lengthCalc(){const result=(+lv.value*units[lf.value]/units[lt.value]).toFixed(6);r.textContent=result;saveHistory("Length Converter",result)}
function tempCalc(){const v=+tvv.value,a=tfm.value,b=ttm.value;if(!Number.isFinite(v)){r.textContent="Enter a value.";return}const c=a==="c"?v:a==="f"?(v-32)*5/9:v-273.15,out=b==="c"?c:b==="f"?c*9/5+32:c+273.15,result=out.toFixed(2);r.textContent=result;saveHistory("Temperature Converter",result)}
function randomCalc(){let a=+mn.value,b=+mx.value;if(a>b)[a,b]=[b,a];const result=`Random number: ${Math.floor(Math.random()*(b-a+1))+a}`;r.textContent=result;saveHistory("Random Number",result)}
function countdown(){let n=+sec.value;if(n<1)return;r.textContent=n;clearInterval(window.tmr);window.tmr=setInterval(()=>{r.textContent=--n;if(n<=0){clearInterval(window.tmr);notify("Countdown finished.")}},1000)}
async function copyText(text){try{await navigator.clipboard.writeText(text);notify("Copied to clipboard.")}catch(e){notify("Copy was blocked by the browser.")}}
function saveFileRecord(file){if(!file)return;let records=JSON.parse(localStorage.getItem(FILE_KEY)||"[]");records.unshift({id:Date.now(),name:file.name,size:file.size,type:file.type||"Unknown",time:new Date().toLocaleString()});records=records.slice(0,50);localStorage.setItem(FILE_KEY,JSON.stringify(records));renderFileRecords();notify(`File record saved: ${file.name}`)}
function renderFileRecords(){const el=document.getElementById("fileRecords");if(!el)return;const records=JSON.parse(localStorage.getItem(FILE_KEY)||"[]");el.innerHTML=records.length?records.map(x=>`<div class="historyItem"><b>📄 ${escapeHtml(x.name)}</b><span>${escapeHtml(x.type)} · ${(x.size/1024).toFixed(1)} KB</span><small>${escapeHtml(x.time)}</small></div>`).join(""):"<p class='muted'>No file records yet.</p>"}

const historySection=document.createElement("section");historySection.className="recordPanel";historySection.innerHTML=`<div class="recordHead"><div><span class="eyebrow">MY RECORD</span><h2>Calculation History</h2></div><div class="recordActions"><button class="smallBtn" onclick="enableNotifications().then(()=>notify('Notifications are enabled when your browser allows them.'))">🔔 Notifications</button><button class="smallBtn" onclick="exportHistory()">⬇ Export</button><button class="smallBtn danger" onclick="clearHistory()">Clear</button></div></div><div id="historyList" class="historyList"></div>`;
document.getElementById("about").before(historySection);renderHistory();
